---
- name: Install and start Apache webserver.
  hosts: all
  become: true

  tasks:
    - name: Install apache webserver package.
      yum:
        name: httpd
        state: present
        
    - name: Start apache webserver
      service:
        name: httpd
        state: started
        enabled: true

    - name: Open HTTP service in firewall.
      firewalld:
        service: http
        state: enabled
